# Generated by Django 4.2.1 on 2023-06-19 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Delivery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('delivery_cost', models.DecimalField(decimal_places=2, max_digits=6)),
                ('order_status', models.CharField(max_length=32)),
                ('delivery_duration', models.DurationField()),
                ('delivery_person', models.CharField(max_length=32)),
                ('delivery_method', models.CharField(max_length=32)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_updated', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
