# Generated by Django 3.2.12 on 2023-08-04 05:16

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Order', '0003_order_customer'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('customer', '0002_customers_user'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Customers',
            new_name='Customer',
        ),
    ]
