# Generated by Django 3.2.12 on 2023-07-13 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Order', '0003_order_customer'),
    ]

    operations = [
        migrations.CreateModel(
            name='Shipments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(auto_created=True)),
                ('shipping_services', models.DateField(auto_created=True)),
                ('shipping_location', models.CharField(max_length=32)),
                ('shipping_method', models.CharField(max_length=32)),
                ('handling_time', models.DurationField()),
                ('transit_time', models.DurationField()),
                ('date_updated', models.DateTimeField(auto_now=True)),
                ('Order', models.ManyToManyField(to='Order.Order')),
            ],
        ),
    ]
