# Generated by Django 3.2.12 on 2023-08-04 05:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Order', '0003_order_customer'),
        ('Shipment', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Shipments',
            new_name='Shipment',
        ),
    ]
