# Generated by Django 3.2.12 on 2023-07-13 17:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0002_customers_user'),
        ('Order', '0002_auto_20230713_1650'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='customer',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='customer.customers'),
            preserve_default=False,
        ),
    ]
